go.property("MIN_ZOOM", 5)
go.property("MAX_ZOOM", 15)

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	local zoom = go.get("#camera", "orthographic_zoom")
	if action_id == hash("up") and zoom < self.MAX_ZOOM and action.value == 1 then
		go.set("#camera", "orthographic_zoom", zoom + 1)
	end
	if action_id == hash("down") and zoom > self.MIN_ZOOM and action.value == 1 then
		go.set("#camera", "orthographic_zoom", zoom - 1)
	end
end
